// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQAocPLSimMbXKK0WrEdcUH1So4Woovqc',
    appId: '1:693141663679:web:348ff402376b7054aabb0a',
    messagingSenderId: '693141663679',
    projectId: 'dairyqueen-a757b',
    authDomain: 'dairyqueen-a757b.firebaseapp.com',
    storageBucket: 'dairyqueen-a757b.firebasestorage.app',
    measurementId: 'G-4W7D0E6813',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9lWafRfWMKOlMMXzTq5VhUh4RstHHb5M',
    appId: '1:693141663679:android:97026e1abfcb11ebaabb0a',
    messagingSenderId: '693141663679',
    projectId: 'dairyqueen-a757b',
    storageBucket: 'dairyqueen-a757b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRV_zrbNucT-vCgtiGfif3oBBQ2713YdA',
    appId: '1:693141663679:ios:d167a3a857fbd8eeaabb0a',
    messagingSenderId: '693141663679',
    projectId: 'dairyqueen-a757b',
    storageBucket: 'dairyqueen-a757b.firebasestorage.app',
    iosBundleId: 'com.example.dairyqueen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRV_zrbNucT-vCgtiGfif3oBBQ2713YdA',
    appId: '1:693141663679:ios:d167a3a857fbd8eeaabb0a',
    messagingSenderId: '693141663679',
    projectId: 'dairyqueen-a757b',
    storageBucket: 'dairyqueen-a757b.firebasestorage.app',
    iosBundleId: 'com.example.dairyqueen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQAocPLSimMbXKK0WrEdcUH1So4Woovqc',
    appId: '1:693141663679:web:71b2d6ebcf44a7e1aabb0a',
    messagingSenderId: '693141663679',
    projectId: 'dairyqueen-a757b',
    authDomain: 'dairyqueen-a757b.firebaseapp.com',
    storageBucket: 'dairyqueen-a757b.firebasestorage.app',
    measurementId: 'G-XPZ00F26ZL',
  );
}
